### ISSUE TITLE
Prediction could not be found "predictions/coronacases_001.nii.gz"

### ISSUE THREAD

**Issue by bensonsin998** [frankkramer-lab/covid19.MIScnn#14]
Hello!

I would like to know what's wrong when I was going to run the run_evaluation.py. It said that "Prediction could not be found "predictions/coronacases_001.nii.gz""

Thanks!

<img width="733" alt="Screenshot 2020-11-25 at 6 30 03 PM" src="https://user-images.githubusercontent.com/56331577/100215660-3e0d2180-2f4c-11eb-99f5-5ba4f061b8c4.png">

**Comment by muellerdo** [comment]
Hello @bensonsin998,

did you receive any errors or exceptions when computing the predictions?

Cheers,
Dominik
