### ISSUE TITLE
How to Make Predictions of a set of new images with the trained model and save it as nii file? What is the procedure? 

### ISSUE THREAD

**Issue by anirban1513** [frankkramer-lab/covid19.MIScnn#17]

**Comment by muellerdo** [comment]
Hey @anirban1513,

I would recommend checking out [MIScnn](https://github.com/frankkramer-lab/MIScnn) on how to load models and run predictions on new data.

Then you just have to modify the run_miscnn.py script accordingly.
Probably recommended to implement some ensemble learning approach to sum up the predictions of the different folds into a single one to obtain best performance.

But we do not provide in detail support here for doing this.
Our support focus in this repository is on reproducing this analysis for our paper.

Cheers,
Dominik Müller
